# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Socket Lab - MTE - Swift/SocketClient

variables:
    repoName: 'tutorial-mte-socket-swift-ios'
    projDir: '$(repoName)/TutorialMTE'
    system_accesstoken: $(System.AccessToken)
    scheme: 'SocketClient'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    workspace: 'SocketClient.xcodeproj'

resources:
  repositories:
  - repository: mteDemoLib
    type: git
    name: Eclypses/package-mte-trial-lib-ios
  - repository: mteWrapper
    type: git
    name: Eclypses/package-swift-mte-ios

pool: 'MTE-MacOS'

steps:

- checkout: self
  displayName: 'Checkout SocketClient'
  clean: true
  persistCredentials: true
- checkout: mteDemoLib
  displayName: 'Checkout Mte Trial Library Framework'
  clean: true
- checkout: mteWrapper
  displayName: 'Checkout Mte Wrapper Files'
  clean: true
    
- task: CopyFiles@2
  displayName: 'Copy MTE Library Framework'
  inputs:
    SourceFolder: 'package-mte-trial-lib-ios/Sources/Mte'
    Contents: 'mte.xcframework/**'
    TargetFolder: '$(projDir)/MTE/lib'
    CleanTargetFolder: true
    OverWrite: true
    
- task: CopyFiles@2
  displayName: 'Copy MTE Header Files'
  inputs:
    SourceFolder: 'package-mte-trial-lib-ios/Sources/Mte/include'
    Contents: '**'
    TargetFolder: '$(projDir)/MTE/include'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy MTE Wrapper Files'
  inputs:
    SourceFolder: 'package-swift-mte-ios'
    Contents: 'Core/**'
    TargetFolder: '$(projDir)/MTE'
    flattenFolders: true
    CleanTargetFolder: false
    OverWrite: true

- task: Xcode@5
  displayName: 'Clean, Build And Test SocketClient'
  inputs:
    actions: 'clean build test'
    scheme: '$(scheme)'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    xcWorkspacePath: '$(projDir)/SocketClient/$(workspace)'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 11 Pro Max'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'

- task: DeleteFiles@1
  displayName: 'Delete unnecessary files before push to public remote'
  inputs:
    SourceFolder: $(repoName)
    Contents: |
      .gitignore
      **/*.yml

- script: |
    git add .
    git commit -am 'Commit unnecessary file deletion'
  displayName: 'Commit unnecessary file deletion'
  workingDirectory: $(repoName)

- script: |
    git push https://nzkomtwqfr46wdlfw5omsj4olbn4zwhusarcpxpoux7zdoohltjq@dev.azure.com/eclypses/Private_Test/_git/tutorial-mte-socket-swift-ios HEAD:master --force
  displayName: 'Push to public repo'
  workingDirectory: $(repoName)
